services:
  wordpress:
    image: wordpress:latest  # Replace with a valid tag (e.g., `6.5` or `php8.2`)
    restart: always
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-project/wp-content:/var/www/html/wp-content
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini

  db:
    image: mysql:5.7
    platform: linux/amd64  # Force AMD64 emulation on ARM64
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini

volumes:
  db_data: